[package]
name = "rtltcp"
description = "A rust implementation of rtl-tcp with better buffering and support for systemd socket activation."
version = "0.6.1"
authors = ["Niclas Hoyer <info@niclashoyer.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/niclashoyer/rtltcp"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["daemon_systemd"]
daemon_systemd = ["listenfd", "systemd"]

[dependencies]
ipnet = "=2.4.0"
rtlsdr_mt = "=2.1.0"
tracing = "=0.1.40"
tracing-subscriber = "=0.3.18"
ctrlc = "=3.4.0"
clap = { version = "=4.5.0", features = ["derive"] }
listenfd = { version = "=1.0.0", optional = true }
systemd = { version = "=0.10.1", optional = true }

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
