name: CI # Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y librtlsdr-dev libsystemd-dev
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace --features daemon_systemd

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y librtlsdr-dev libsystemd-dev
      - uses: Swatinem/rust-cache@v2
      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --all-features --workspace --examples

  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y librtlsdr-dev libsystemd-dev
      - uses: Swatinem/rust-cache@v2
      - name: Publish dry run
        run: cargo publish --dry-run --allow-dirty

  msrv:
    name: MSRV Test (1.75)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.75
        with:
          components: clippy
      - name: install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y librtlsdr-dev libsystemd-dev
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace --features daemon_systemd
      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y librtlsdr-dev libsystemd-dev
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@cargo-tarpaulin
      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --all-features --workspace --ignore-tests --out Lcov
      - name: Upload to Coveralls
        # upload only if push
        if: ${{ github.event_name == 'push' }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './lcov.info'
